### ISSUE TITLE
`Option::unwrap()` on a `None` value in `transaction.rs` whilst committing/dropping transaction

### ISSUE THREAD

**Issue by reivilibre** [y-crdt/y-crdt#150]
After applying many V1 updates (all of which were generated by Y.js) to a transaction and then committing, Yrs panics.
(This seems to be specific to these updates, since other documents seem to work fine.)

```rust
            // doc_updates: Vec<Vec<u8>>
            let ydoc = Doc::new();
            {
                let mut txn = ydoc.transact();
                debug!("{} updates to apply.", doc_updates.len());
                for update_bytes in doc_updates {
                    let update = Update::decode_v1(&update_bytes)?;
                    txn.apply_update(update);
                }
            } // <---- backtrace points to this line
```

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/quail/.cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.10.0/src/transaction.rs:562:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:755:21
   4: yrs::transaction::Transaction::commit
             at /home/quail/.cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.10.0/src/transaction.rs:562:26
   5: <yrs::transaction::Transaction as core::ops::drop::Drop>::drop
             at /home/quail/.cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.10.0/src/transaction.rs:698:9
   6: core::ptr::drop_in_place<yrs::transaction::Transaction>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
```

`yrs` version 0.10.0

If it would be useful, I can give you some reproduction code along with the updates that I'm applying — there are 423 of them but most of them are tiny — I can probably tar them up and write some code that loads them with `std::fs::read` or so?
Let me know — I don't know if this is 'obvious' to someone who knows the code or whether you would actually appreciate that.

**Comment by Horusiath** [comment]
This should be fixed in release v0.10.1. Feel free to reopen the issue if it's not the case.
