### ISSUE TITLE
Panic when Inserting cyrillic text

### ISSUE THREAD

**Issue by zaynetro** [y-crdt/y-crdt#231]
I've noticed that Yrs panics from time to time depending on the offset. It seems to happen with cyrillic text.

First of all, `ytext::len` reports wrong length. Second, inserting at random offsets panics depending on the offset. Example below panics with `11` but doesn't panic with `10` or `12`.

```rust
    #[test]
    fn test_yrs_text_ru() {
        let doc = yrs::Doc::new();
        let ytext = doc.get_or_insert_text("text");
        {
            let txn = &mut doc.transact_mut();
            ytext.push(txn, "Привет! One");
            // to_string="Привет! One"  len=17
            // This line panics.
            ytext.insert(txn, 11, "\nTwo");
        }
    }
```

Panic log:

```
failures:

---- timeline::card::tests::test_yrs_text_ru stdout ----
thread 'timeline::card::tests::test_yrs_text_ru' panicked at 'attempt to subtract with overflow', .cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.14.1/src/block.rs:1286:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/01fbc5ae789fc0c7a2da71d3cd908451f175e4eb/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/01fbc5ae789fc0c7a2da71d3cd908451f175e4eb/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/01fbc5ae789fc0c7a2da71d3cd908451f175e4eb/library/core/src/panicking.rs:111:5
   3: yrs::block::SplittableString::block_offset
             at .cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.14.1/src/block.rs:1286:21
   4: yrs::types::text::find_position
             at .cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.14.1/src/types/text.rs:415:33
   5: yrs::types::text::Text::insert
             at .cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.14.1/src/types/text.rs:87:32
   6: tests::test_yrs_text_ru
             at ./test.rs:792:13
```

Questions:

1. How to calculate offset so that insert won't panic?

**Comment by zaynetro** [comment]
OK sorry for rushed issue creation.

This is an example of a difference between `String::len()` and `String::chars().count()`. In my case UI gives me offset in chars so I need to convert it to byte offset.

**Comment by Horusiath** [comment]
Inside of Doc options you can set what kind of encoding do offsets use. See: https://github.com/y-crdt/y-crdt/blob/2692e427a40ffb07d303ad80ce9339b5dab8ed7e/yrs/src/doc.rs#L473

**Comment by zaynetro** [comment]
That is nifty. Would be nice to know about it when reading Text docs.

I have added docs regarding this feature: https://github.com/y-crdt/y-crdt/pull/232
