### ISSUE TITLE
ywasm txn.free(): "Error: recursive use of an object detected which would lead to unsafe aliasing in rust"

### ISSUE THREAD

**Issue by mweidner037** [y-crdt/y-crdt#237]
I tried updating [crdt-benchmarks](https://github.com/dmonad/crdt-benchmarks) from 0.9.1 to 0.14.1 (latest). After some minor changes to match API updates (notably `beginTransaction` -> `readTransaction`), the code fails with:
```
Error: recursive use of an object detected which would lead to unsafe aliasing in rust
    at module.exports.__wbindgen_throw (crdt-benchmarks/node_modules/ywasm/ywasm.js:3837:11)
    at wasm_bindgen::throw_str::h778c888b6b19e0c6 (wasm://wasm/00318896:wasm-function[1536]:0xa2058)
    at wasm_bindgen::__rt::borrow_fail::hfbd747a4c510f31b (wasm://wasm/00318896:wasm-function[1535]:0xa204d)
    at __wbg_ytransaction_free (wasm://wasm/00318896:wasm-function[998]:0x992ec)
    at YTransaction.free (crdt-benchmarks/node_modules/ywasm/ywasm.js:2251:14)
    at YwasmCRDT.transact (crdt-benchmarks/benchmarks/ywasm/factory.js:119:18)
    at YwasmCRDT.insertText (crdt-benchmarks/benchmarks/ywasm/factory.js:90:10)
    at file:///crdt-benchmarks/js-lib/b1.js:58:28
    at file:///crdt-benchmarks/js-lib/b1.js:29:11
    at benchmarkTime (file:///crdt-benchmarks/js-lib/utils.js:45:3)
```
The offending line is the `txn.free()` [here](https://github.com/dmonad/crdt-benchmarks/blob/12b4e90db7fe9af5b4544225b62320c3edb5fffb/benchmarks/ywasm/factory.js#L120). I believe its usage matches the doc's example [here](https://github.com/y-crdt/y-crdt/blob/dac997ab13ac9801c05b99e524cba0a8adc52563/ywasm/src/lib.rs#L147-L154) (except for `beginTransaction` -> `readTransaction`).

The issue begins with version 0.13.0, the same version that renamed `beginTransaction`.

**Comment by Horusiath** [comment]
This is kinda specific bug for wasm_bindgen, caused when you try to free an object that still has active references to, quite often I managed to run into this issue because WASM object was captured by the closure while being released. 

I'll take a look into this and try to update the examples.

**Comment by Horusiath** [comment]
AFAIK this issue has been solved by now - we use Seph Gentle's real-life editing trace examples for tests and benchmarks for both yrs and ywasm. Let us know if this issue happens again.
