### ISSUE TITLE
Question about ytransaction_apply_v2

### ISSUE THREAD

**Issue by SebastianStehle** [y-crdt/y-crdt#328]
Hi,

I am working with a C# wrapper over your rust library and I have a question about the an error I get.

I get an update from the client, which is just an byte array. it is basically encoded as followed:

* Length (variable length encoding)
* Content

So I decode it and get the content as byte array, which I then pass to your lib.  But I get the following error: 

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 2', yrs\src\updates\decoder.rs:250:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src/panicking.rs:162:5
   3: yrs::updates::decoder::DecoderV2::read_usize
             at D:\_other\y-crdt\yrs\src\updates\decoder.rs:250:21
   4: yrs::updates::decoder::DecoderV2::read_buf
             at D:\_other\y-crdt\yrs\src\updates\decoder.rs:264:19
   5: yrs::updates::decoder::DecoderV2::new
             at D:\_other\y-crdt\yrs\src\updates\decoder.rs:218:26
   6: yrs::updates::decoder::Decode::decode_v2
             at D:\_other\y-crdt\yrs\src\updates\decoder.rs:18:27
   7: ytransaction_apply_v2
             at D:\_other\y-crdt\yffi\src\lib.rs:1120:11
```

So for me it looks like the data is already preencoded for the websocket protocol. is this right?

**Comment by SebastianStehle** [comment]
Sorry, I have just used the wrong method. V2 instead of V1. But I think the process should not crash when this happens.
