### ISSUE TITLE
ywasm examples aren't working

### ISSUE THREAD

**Issue by rgbkrk** [y-crdt/y-crdt#337]
The example in the readme has a few missing pieces namely that `beginTransaction` doesn't exist anymore and `transact` isn't being called below:

```typescript
import {YDoc, encodeStateVector, encodeStateAsUpdate, applyUpdate} from 'ywasm';

YDoc.prototype.transact = callback => {
    const txn = this.beginTransaction()
    try {
        return callback(txn)
    } finally {
        txn.free()
    }
}

const doc = new YDoc()
const text = doc.getText('name')

// append text to our collaborative document
text.insert(txn, 0, 'hello world')

// simulate update with remote peer
const remoteDoc = new YDoc()
const remoteText = remoteDoc.getText('name')

// in order to exchange data with other documents 
// we first need to create a state vector
const remoteSV = encodeStateVector(remoteDoc)
// now compute a differential update based on remote document's state vector
const update = encodeStateAsUpdate(doc, remoteSV)
// both update and state vector are serializable, we can pass them over the wire
// now apply update to a remote document
applyUpdate(remoteDoc, update)

const str = remoteText.toString(txn)
console.log(str)
```

I looked into an example inside of `ywasm/src/lib.rs` and it seems the interface is now:

```
// example.mjs
import {YDoc} from 'ywasm'

const doc = new YDoc()

const text = doc.getText('name')

const txn = doc.readTransaction()
try {
    text.insert(txn, 0, 'hello world')
} finally {
    txn.free()
}
```

However that errors out in both node and deno with a memory access out of bounds.

```
Stack trace:
RuntimeError: memory access out of bounds
    at dlmalloc::dlmalloc::Chunk::size::h48e91a2c5adb13a6 (wasm://wasm/00378db6:1:751711)
    at __rdl_realloc (wasm://wasm/00378db6:1:382950)
    at __rust_realloc (wasm://wasm/00378db6:1:750065)
    at __wbindgen_realloc (wasm://wasm/00378db6:1:745167)
    at passStringToWasm0 (file:///Users/kai/Library/Caches/deno/npm/registry.npmjs.org/ywasm/0.16.10/ywasm.js:119:15)
    at YText.insert (file:///Users/kai/Library/Caches/deno/npm/registry.npmjs.org/ywasm/0.16.10/ywasm.js:2109:26)
    at <anonymous>:7:8
```

This is all with `ywasm@0.16.10` from npm

**Comment by Horusiath** [comment]
Yes the code here is probably stale and should be updated to match the latest version.
