### ISSUE TITLE
Error occurs in yffi when inserting nested Maps into document

### ISSUE THREAD

**Issue by twaddell** [y-crdt/y-crdt#447]
Inserting a more complex nested map into a document appears to work fine in yrs but fails in yffi.
I am running on a Windows environment.

The following test case in yffi fails
```
TEST_CASE("YMap multiple nested maps") {
    YDoc* doc = ydoc_new_with_id(1);
    Branch* map = ymap(doc, "map");
    YTransaction* txn = ydoc_write_transaction(doc, 0, NULL);

    char* key = (char*)"text";
    YInput value = yinput_string("Nested data");
    YInput innerMap = yinput_ymap(&key, &value, 1);

    char* key2 = (char*)"innerMap";
    YInput outerMap = yinput_ymap(&key2, &innerMap, 1);

    ymap_insert(map, txn, "outerMap", &outerMap);
    int length = ymap_len(map, txn);
    ytransaction_commit(txn);
    REQUIRE(length == 1);

    ydoc_destroy(doc);
}
```

The following error is shown in the console when this test case is run:
```
thread '<unnamed>' panicked at yffi\src\lib.rs:2488:17:
Unrecognized YVal value tag.
```

Simplifying the nesting in yffi will allow the test to pass
```
TEST_CASE("YMap nested map") {
    YDoc* doc = ydoc_new_with_id(1);
    Branch* map = ymap(doc, "map");
    YTransaction* txn = ydoc_write_transaction(doc, 0, NULL);

    char* key = (char*)"text";
    YInput value = yinput_string("Nested data");
    YInput innerMap = yinput_ymap(&key, &value, 1);

    ymap_insert(map, txn, "innerMap", &innerMap);
    int length = ymap_len(map, txn);
    ytransaction_commit(txn);
    REQUIRE(length == 1);

    ydoc_destroy(doc);
}
```

The following test case in yrs passes
```
  #[test]
  fn map_nested() {
      let d1 = Doc::with_client_id(1);
      let m1 = d1.get_or_insert_map("map");
      let mut t1 = d1.transact_mut();

      let mut innerMap: HashMap<String, _> = HashMap::new();
      innerMap.insert("text".to_owned(), "Nested data");
      
      let mut outerMap: HashMap<String, _> = HashMap::new();
      outerMap.insert("innerMap".to_owned(), MapPrelim::from(innerMap));

      m1.insert(&mut t1, "outerMap".to_owned(), MapPrelim::from(outerMap));
      
      assert_eq!(m1.len(&t1), 1);
  }
```

I originally ran into this issue using the dotnet wrapper but have traced it back to the yffi layer (https://github.com/y-crdt/ydotnet/issues/99). It's been a few years since I last did any c++ so please let me know if there is something obviously wrong with the test cases.

**Comment by twaddell** [comment]
Ran the failing test with RUST_BACKTRACE=1 which output the following additional information:

```
thread '<unnamed>' panicked at yffi\src\lib.rs:2488:17:
Unrecognized YVal value tag.
stack backtrace:
   0: std::panicking::begin_panic<ref$<str$> >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\panicking.rs:686
   1: yrs::YInput::into
             at X:\y-crdt\yffi\src\lib.rs:2488
   2: yrs::impl$11::integrate
             at X:\y-crdt\yffi\src\lib.rs:2565
   3: yrs::transaction::TransactionMut::create_item<yrs::YInput>
             at X:\y-crdt\yrs\src\transaction.rs:729
   4: yrs::types::map::Map::insert<yrs::types::map::MapRef,alloc::string::String,yrs::YInput>
             at X:\y-crdt\yrs\src\types\map.rs:173
   5: yrs::ymap_insert
             at X:\y-crdt\yffi\src\lib.rs:1571
   6: _DOCTEST_ANON_FUNC_19
             at .\main.cpp:301
   7: doctest::Context::run
             at .\include\doctest.h:6502
   8: main
             at .\include\doctest.h:6587
   9: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  10: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  11: __scrt_common_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
  12: mainCRTStartup
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
  13: BaseThreadInitThunk
  14: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
===============================================================================
```

**Comment by Horusiath** [comment]
Thanks. I'll take a look at this.

**Comment by SebastianStehle** [comment]
It seems the problem has been solved but not fixed yet?

**Comment by Horusiath** [comment]
@SebastianStehle it's been released already.

**Comment by SebastianStehle** [comment]
Github does not show a release, only a tag. Therefore I was confused.

**Comment by PhilippCh** [comment]
Could it be that the same issue still exists for inserting nested arrays? I'm trying to insert the following object into an empty array `tasks` that exists on the root doc.

```
{
  "uuid": "any-uuid"
  "tags": []
}
```

This fails with the same error as mentioned above. When I remove the `tags` array of the object I want to insert into the `tasks` array, the error disappears.

**Comment by PhilippCh** [comment]
It appears that this (or something related) is still an issue when creating a `yinput_json_array` inside a `yinput_json_object`. An example would be trying to add the following to a doc:

```json
{
  "name": "Test",
  "testArray": ["Test string"]
}
```

When omitting the `testArray` while creating the input object, it works fine, otherwise it throws the same error that is mentioned in this issue.

any help would be greatly appreciated!
